#!/bin/bash
#SBATCH --job-name=batch_job
#SBATCH --output=logs/job_%A_%a.out
#SBATCH --partition=gpu_a100
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --gpus=1
#SBATCH --time=1-00:00:00

module load 2023
module load OpenMPI/4.1.5-GCC-12.3.0
module load CUDA/12.1.1
module load PLUMED/2.9.0-foss-2023a

# Define paths
TASK_ID_PADDED=$(printf '%06d' $SLURM_ARRAY_TASK_ID)
SHARED_PATH="/scratch-shared/ldkam/md_runs/task_${TASK_ID_PADDED}"
LOCAL_PATH="/scratch-local/$USER/task_${TASK_ID_PADDED}"

# Create and copy input files to local scratch
mkdir -p "$LOCAL_PATH"
cp -r "$SHARED_PATH"/* "$LOCAL_PATH"/

# Go to local scratch
cd "$LOCAL_PATH" || exit 1

# Run calculation on local scratch
srun ~/lammps/build-a100-plumed/lmp -k on g 1 -sf kk -pk kokkos newton on neigh half -in input.lmp

# Copy results back to shared scratch
cp -r "$LOCAL_PATH"/* "$SHARED_PATH"/

# Optional: clean up local scratch
rm -rf "$LOCAL_PATH"
